### ISSUE TITLE
templ integration example

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/gcss#3]
https://github.com/a-h/templ/issues/740#issuecomment-2127664137

**Comment by stuartaccent** [comment]
this will more likely be covered off using an example nd not for part of the main package

**Comment by stuartaccent** [comment]
[#](https://github.com/AccentDesign/gcss/commit/7878d5b6b82ed61e3b16373d3f07cf0ebb2c97f2)

**Comment by stuartaccent** [comment]
Done

**Comment by yonas** [comment]
4a37f93
